### ISSUE TITLE
If only have on type of field, don't ask for type

### ISSUE THREAD

**Issue by jenstornell** [TimOetting/kirby-builder#13]
I only added one type. In this case it does not need to ask of what type I want to add.

![image](https://cloud.githubusercontent.com/assets/927011/13665321/2b76b664-e6ac-11e5-9179-b11d1838bd46.png)

**Comment by dionysiusmarquis** [comment]
Does this relate: https://github.com/TimOetting/kirby-builder/pull/2?

**Comment by TimOetting** [comment]
Well, #2 was closed with the hint that for only one type of fieldsets the original structure field would do the job. However, since the builder field also comes with the additional _fileUrl field I see a point for handling the case of only one fieldset type as mentioned. 

I will add this feature during the next days

**Comment by jenstornell** [comment]
Agree!

It's not that heavy to click two times for one item, but when adding for example 30 image items, then that would be 60 clicks instead of 30 so this fix will make a big difference.

+1

**Comment by jenstornell** [comment]
![image](https://cloud.githubusercontent.com/assets/927011/16372766/d77c89fa-3c4e-11e6-9757-3a6f7d12c1e8.png)

Also hide this info if there is only one field type.

**Comment by TimOetting** [comment]
This issue is related to old version for Kirby 2 and will therefore not be fixed anymore. I am currently closing all the old reports to clean up the the issues section here on github.
