### ISSUE TITLE
Page builder block not saving content in Kirby 2.3.2

### ISSUE THREAD

**Issue by Will0489** [TimOetting/kirby-builder#43]
Several of our sites that are/were still running Kirby 2.3.2 were experiencing issues with the page builder (using the current master branch) **not saving content from newly added blocks or when editing existing blocks**. We were unable to identify as to why this happens but upgrading to 2.4.1 seems to resolve the issue.

It might be worthwhile to either investigate this situation under 2.3.2 (and maybe other versions below or between that one and 2.4.1) or give a notice that there may be some issues using the page builder under that configuration. We were lucky that all of our Kirby sites are updatable via the git submodule approach.

All page builder settings were taken from the readme in the repository, so there were no special or exotic block setups, just a single basic textbased block with a basic snippet as explained in the readme.

**Comment by TimOetting** [comment]
Thanks for the the hint. This seems to be a result from an update on the ajax call. As pointed out in #35, Kirby had a bug that let to incorrect handling of post data. The update of the builder field required this bug to be fixed, which was the case since Kirby 2.4.1 . I missed to update the Readme accordingly. I just updated it.
