### ISSUE TITLE
Structured field

### ISSUE THREAD

**Issue by getflourish** [TimOetting/kirby-builder#46]
What’s needed to make this work? Happy to contribute to make it work if I know where the challenges are and what needs to be done :)

**Comment by dionysiusmarquis** [comment]
Hi,

this change is quite a big one. The builder is actually an extended structure itself. If you browse through the sources you will see that every part is an extension of the Kirby `Structure` and `StructureField`. To get it working, structures inside a structure have to be implemented in the Kirby core (https://github.com/getkirby/panel/issues/510). Structures doesn't even have a scope in the panel ajax calls https://github.com/TimOetting/kirby-builder/issues/30 etc.

To contribute, you should begin in the Kirby/Panel core. I think there is already something on the roadmap like removing modals to make such things possible.

Just to note: There is also a module-plugin extension wich is build on top of the idea to have a subpage/module for every entry https://github.com/lukaskleinschmidt/kirby-sortable

**Comment by TimOetting** [comment]
Hey all together,

I am currently working on an entire new implementation of the builder field, especially to get nesting working. As dionysiusmarquis pointed out, the problem with the panel lies deep inside the Kirby core. Therefore I decided to get rid of the remaining dependencies​ to the panel field.

I cannot give you a clear roadmap for the new Kirby field by now. Maybe there will be a first release within the next weeks.

**Comment by dinealbrecht** [comment]
Hey! I'm also extremely keen on a working structure field. Thought I'd check in on ETA? :)

**Comment by mpatzner** [comment]
I am curious about an ETA as well. 👍

**Comment by alvarovinagre** [comment]
Same here. Is there any update on this?

**Comment by TimOetting** [comment]
Hey folks,

there will not be a bigger update on the kirby builder for kirby 2.x . Along with my efforts to rebuild the plugin, Kirby 3 has been announced a while ago. Kirby's next major version will hopefully be released in early 2018. 

It makes much more sense for me now to concentrate on the new architecture provided by kirby 3 instead of hacking this feature into kirby 2.x that will be deprecated in a few month . I am planning to have the new Kirby builder released along with Kirby 3's release date.

**Comment by alvarovinagre** [comment]
Thank you for your reply @TimOetting, looking forward to it!
